### ISSUE TITLE
Reference first-timers-only issues.

### ISSUE THREAD

**Issue by musically-ut** [melanierichards/just-build-websites#14]
[First Timers Only](http://www.firsttimersonly.com/) are special kind of issues which usually involve a relatively minor change, but can provide a good platform for beginners to start their OSS journey. Many of these issues are for fixing JS or making changes to websites (HTML/CSS).

I wrote a Twitter bot [@first_tmrs_only](https://twitter.com/first_tmrs_only), which tweets about such issues as soon as they appear on Github search results.

This is a bit more concrete than _"Look at other people's code"_. Do you reckon that it will find a place among the list of recommendations?

**Comment by melanierichards** [comment]
Hi @musically-ut! Not sure how I missed this issue but I think this would be a great addition to the list, probably somewhere further up top. Would you like to submit a PR with that addition? (I can also add it if you prefer)
